name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Read .nvmrc 📄
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Setup node 🛠
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install 📦
        run: yarn install

      # - name: Lint 🕵️‍♂️
      #   run: yarn lint

      # - name: Test 👨‍🔬
      #   run: yarn test

      - name: Build 👷‍♂️
        run: yarn build

      - name: Deploy 🚚
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
